#!/bin/bash

REGEX_BRANCH_NAME="((release|bugfix|hotfix|feature|story|ci|docs)\/(SN)-[0-9]+)|(T[0-9]+)|(misc\/[a-z|0-9|-]*)"
BRANCH_NAME=$(echo $(git rev-parse --abbrev-ref HEAD) | grep -o -E "$REGEX_BRANCH_NAME")
TASK_ID=${BRANCH_NAME##*/}

if [[ -z "$BRANCH_NAME" ]]; then
    echo "[pre-commit-hook] Your branch name is incorrect. Allowed regex: $REGEX_BRANCH_NAME"
    exit 1
else
    FILE=`cat "$1"`
    echo "$TASK_ID | $FILE" > "$1"
fi